name: catbreeds_riverpod
description: A application for cats breeds information with Flutter and Riverpod
  with Domain Driven Design.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  card_loading: ^0.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.10
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.6
  go_router: ^8.0.1
  google_fonts: ^4.0.4
  rive: ^0.11.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/languages/
    - assets/animations/

flutter_native_splash:
  color: "#e8f8c8"
  image: assets/app_icon.png
  branding: assets/app_title.png

  android_12:
    color: "#e8f8c8"
    image: assets/app_icon.png
    branding: assets/app_title.png

  fullscreen: true
